### ISSUE TITLE
What's the relationship between your definition of deep gaussian process and original one?

### ISSUE THREAD

**Issue by Fangwq** [duvenaud/deep-limits#4]
Hi, I read the paper <<Deep Gaussian Processes>> written by Andreas C. Damianou and Neil D. Lawrence. And I am a little confused about the relationship and difference between you two. Personally, I think your definition is more apt to understand. Can you say something about your   understanding ? Does Damianou's deep GP also has pathology you mentioned in your paper?

**Comment by duvenaud** [comment]
Good catch. I think what they introduced was actually a deep GP-LVM, which has a 2-layer deep GP as a part of a density model.  I think it was a confusing choice and inconsistent with the standard meanings of other words, which is why I felt comfortable proposing my own (more general) definition.  Damianou's deep GP would probably have the same pathologies if they used many layers.
